### ISSUE TITLE
OAuth verification email - missing image, replyto email address

### ISSUE THREAD

**Issue by stevedebrun** [sos-bend/web#13]
Need to fix broken image reference at the top. also, do we want the email to come from an sosbend.com email address?

![Screen Shot 2020-04-07 at 12 42 23](https://user-images.githubusercontent.com/10576697/78712608-b778d680-78cd-11ea-93da-9768364c6091.png)

**Comment by spolitakis** [comment]
used the heart image, set the from email and personalized the message
