### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by stevedebrun** [sos-bend/web#3]
Update paragraph of text and links in the footer. Check out the latest on Zeplin. Link to appropriate HelpScout pages if we don't cut the HTML. Also, insert the legalese snippet:

©2020 Main Street SOS LLC. All rights reserved.

**Comment by spolitakis** [comment]
I have templates for all of these except About and Our Supporters, which we can improvise with the person who is going to help with the static pages tomorrow/over the weekend.
• Blog will link to the Medium publication Matt created
• Press Materials will link to a public Google Drive folder for now
• The three social icons will link to their respective URLs
• contact@ and help@ will be mailto:'s

<img width="1487" alt="Screen Shot 2020-04-09 at 9 14 41 PM" src="https://user-images.githubusercontent.com/2822080/78996847-4f5b0800-7afa-11ea-8778-1ca955830e0d.png">

**Comment by spolitakis** [comment]
@stevedebrun the email I am using for support is support@sosbend.com not help. It's eveywhere form auth0 and all over the site, I'm not changing it now. We can crate a help@sosbend.com alias later.
