### ISSUE TITLE
Page examples link doesn't work

### ISSUE THREAD

**Issue by mattabrams** [sos-bend/web#32]
![Screen Shot 2020-04-08 at 15 19 21](https://user-images.githubusercontent.com/28972351/78839027-5d027780-79ac-11ea-8ff8-970cbed4bd31.png)

**Comment by spolitakis** [comment]
currently the path/page name for this is "examples" can you ad this to your list if it's not on there, or close if it is

https://sosbend.now.sh/docs/examples

**Comment by stevedebrun** [comment]
The intention was to link to three different claimed business pages. I propose we eliminate for now, and end the text at "...not too tall if you can avoid it."
