### ISSUE TITLE
Ticker questions we need to answer before launch

### ISSUE THREAD

**Issue by mattabrams** [sos-bend/web#34]
What shows up here before any adds (do we list new businesses being added first during phase 1?)

![Screen Shot 2020-04-08 at 15 25 48](https://user-images.githubusercontent.com/28972351/78839387-3d1f8380-79ad-11ea-9744-b651295abc44.png)

**Comment by stevedebrun** [comment]
Two options:

1. We can list new businesses that have signed up
2. The moment we launch for consumers, we give to 5-10 companies that are already onboarded to prime the pump

**Comment by mattabrams** [comment]
My take is not critical path, however (i.e., we can remover the ticker all together for v1?)

**Comment by stevedebrun** [comment]
I vote to keep it if Simon and Jason can build it. It shows life and activity, and we currently don't have any other ways to do that (for example, a ticker on a business' page, etc.).

**Comment by spolitakis** [comment]
Remove it for now
