### ISSUE TITLE
Auth0 login doesn't alert you if you try to sign up and you already have an account  

### ISSUE THREAD

**Issue by davebaiocchi** [sos-bend/web#38]
On the Auth0 Sign Up tab, if you type an existing email and password, a message is displayed saying "We're sorry, something went wrong when attempting to sign up."

Yeah, the thing that went wrong is that I already have an account. This is likely outside our team's control, but this would be a lot more functional if the error message said something like "This email address has already been registered. Please log in using the other tab."

The reason I'm flagging this is that  several times when I was claiming businesses (all from the same browser), I was funneled to the Auto0 log in screen and it always defaulted to the Sign Up tab rather than the Log In tab. I could imagine a few people getting hung up on this step.

**Comment by spolitakis** [comment]
Not sure if I can fix this, but I'll take a look @davebaiocchi

**Comment by spolitakis** [comment]
Now using passwordless so no signup flow
