### ISSUE TITLE
"Search Again" when claiming the same business doesn't work

### ISSUE THREAD

**Issue by davebaiocchi** [sos-bend/web#41]
Okay, maybe this is a small one, but it's definitely a bug. 

1. From the home page, search for a business. 
2. Click the button to claim the business. 
3. On the next screen, see the five steps. If you click the blue link "(search again)" under the business name, a search window appears. If you type & select *the same business* as what was just in there, you get stuck in a soft lock. You'll need to reload the page to continue.

**Comment by stevedebrun** [comment]
Good catch Hulk.

**Comment by davebaiocchi** [comment]
I have been breaking software for years. Had no idea it was a valuable skill.

**Comment by spolitakis** [comment]
+1 @davebaiocchi
