### ISSUE TITLE
Claim Business flow - Redeem credit 4-digit code needs to be unique per business

### ISSUE THREAD

**Issue by stevedebrun** [sos-bend/web#42]
Currently reads for any business:

"When you are at the store, text **4142** to (541)240-8840 or use this QR code to send the text:"

we need to replace "4142" with the unique code generated for that business.

**Comment by spolitakis** [comment]
@jasonwiener can you response to this one please.

**Comment by jasonwiener** [comment]
the 4 digit code to use to redeem is the first 4-chars of the merchant uuid (not Google place id)
